package com.mirkmoon.mapper;

import com.mirkmoon.pojo.RolePermissionKey;

public interface RolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(RolePermissionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission
     *
     * @mbg.generated
     */
    int insert(RolePermissionKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission
     *
     * @mbg.generated
     */
    int insertSelective(RolePermissionKey record);
}